# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ListingLocation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ListingLocation
  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireObjectMapper'
  pod 'Alamofire-SwiftyJSON'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage'
  pod 'ReachabilitySwift', '~> 3'
  pod 'SideMenu'
  pod 'SVProgressHUD'

  target 'ListingLocationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ListingLocationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
